### ISSUE TITLE
In active use?

### ISSUE THREAD

**Issue by ilovezfs** [gmontard/issue-sync-redmine-github#3]
Is this still being used? If not, has it been superseded by something else?

**Comment by gmontard** [comment]
Well it works, we do use it heavily internally @Vodeclic so...

**Comment by ilovezfs** [comment]
@gmontard Thank you for your response. Is there still the limitation that the issue first must be created on the redmine side? The use case I have in mind is this: http://lists.open-zfs.org/pipermail/developer/2016-January/002225.html

**Comment by gmontard** [comment]
@ilovezfs Well yes but you probably could fork it to make it work the other way also, this is just not our use case.

**Comment by ilovezfs** [comment]
@gmontard Thanks! I noticed that the last commit here was Nov 12, 2014. Is that because at this point "it just works" or are there internal improvements/bugfixes that haven't made their way over here?

**Comment by gmontard** [comment]
@ilovezfs Obviously it could be improved but yes basically it works, we've create of thousands automated issue with the tools and use it daily

**Comment by ilovezfs** [comment]
@gmontard Cool. Glad to hear it's worked out well for you guys.
